### PR TITLE
Add sharding.

### PR DESCRIPTION
**Pull request by danjacques**
On LUCI, we're crushing the resources of our builder. The latest issue is OOM errors. This CL adds sharding to PCG, enabling us to break our overall PCG tests into a sequence of consecutive runs. Sharding uses a hash and is opted-in by a Check, which applies some string it derives from each element that it operates on to the sharding function.

Just a thought, plus I wanted to play around with this code base. WDYT?

### CODE REVIEW

**Comment by maruel** [comment]
I think it'd be more appropriate to have a specific fix than a generic sharding functionality.

In this case, it's go test -race that is blowing up the VM's memory capacity. IMHO the best option would be to add -concurrent with the number of concurrent operations that can be done simultaneously. I'd prefer that to the sharding idea, which achieves the same result but in a much more complicated way. So the idea would be that each check that creates a child process would have to lock against a semaphore of -concurrent values.

wdyt?

**Comment by danjacques** [comment]
I think for a single runtime, a concurrent meter is definitely a more concise and effective option. I went with sharding because it is friendlier to Travis' [VM sharding](https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-builds-across-virtual-machines), which seems like a more scalable end-game.

I'll quickly admit I'm not terribly familiar with Travis testing setups, though, so if you think we're good sticking with single-VM testing I'll implement concurrent metering. WDYT?

**Comment by maruel** [comment]
Good question. I didn't know about this but sharding at this level could be done with ci1 and ci2 meta mode. (You can actually invent new modes just fine). This is still less complex than having automatic sharding, which would likely still be very unbalanced.

So yes concurrent metering would be better, at least short term. Change the signature of capture() in checks/checks.go to implement this; I'd make it a method on Options, so you can add the concurrency in checks.Options.

**Comment by danjacques** [comment]
Okay, closing in favor of #5.

**Pull request closed without merging**
